[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
subscription_manager = "ZANo1AAyHkJQN5ghsg8Ft7Ye6d1YWihEbdw1Ed33bip"

[programs.devnet]
subscription_manager = "ZANo1AAyHkJQN5ghsg8Ft7Ye6d1YWihEbdw1Ed33bip"

[programs.testnet]
subscription_manager = "ZANo1AAyHkJQN5ghsg8Ft7Ye6d1YWihEbdw1Ed33bip"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path programs/subscription-manager/Cargo.toml"

[hooks]
