// Copied as-is from target/types/subscription_manager.ts, generated by
// `anchor build`. Regenerate after any Rust program change:
//   cp ../../target/idl/subscription_manager.json src/abi/SubscriptionManagerSolana.json
//   cp ../../target/types/subscription_manager.ts src/abi/SubscriptionManagerSolanaType.ts
// (mirrors tron/README.md's documented ABI-copy step for the TRON side)
//
/**
 * Program IDL in camelCase format in order to be used in JS/TS.
 *
 * Note that this is only a type helper and is not the actual IDL. The original
 * IDL can be found at `target/idl/subscription_manager.json`.
 */
export type SubscriptionManager = {
  "address": "ZANo1AAyHkJQN5ghsg8Ft7Ye6d1YWihEbdw1Ed33bip",
  "metadata": {
    "name": "subscriptionManager",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "Solana port of contracts/SubscriptionManager.sol — pull-payment subscription billing via SPL Token delegate authority"
  },
  "docs": [
    "Solana/Anchor port of contracts/SubscriptionManager.sol — same",
    "pull-payment model (approve once, permissionless keeper charges every",
    "period without the user re-signing), replicated via SPL Token's",
    "delegate-authority mechanism instead of ERC20 allowance. See",
    "docs/mainnet-addresses.md and the Solana integration plan for the full",
    "design rationale (why a PDA can safely act as the delegate, why",
    "charge_due must pre-check before transferring, etc)."
  ],
  "instructions": [
    {
      "name": "cancel",
      "discriminator": [
        232,
        219,
        223,
        41,
        219,
        236,
        220,
        190
      ],
      "accounts": [
        {
          "name": "config"
        },
        {
          "name": "user",
          "signer": true
        },
        {
          "name": "subscription",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  115,
                  117,
                  98,
                  115,
                  99,
                  114,
                  105,
                  112,
                  116,
                  105,
                  111,
                  110
                ]
              },
              {
                "kind": "account",
                "path": "config"
              },
              {
                "kind": "account",
                "path": "user"
              }
            ]
          }
        }
      ],
      "args": []
    },
    {
      "name": "chargeDue",
      "discriminator": [
        107,
        1,
        44,
        49,
        139,
        175,
        199,
        129
      ],
      "accounts": [
        {
          "name": "config",
          "relations": [
            "plan",
            "subscription"
          ]
        },
        {
          "name": "user"
        },
        {
          "name": "plan",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  112,
                  108,
                  97,
                  110
                ]
              },
              {
                "kind": "account",
                "path": "config"
              },
              {
                "kind": "account",
                "path": "subscription.planId",
                "account": "subscription"
              }
            ]
          }
        },
        {
          "name": "subscription",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  115,
                  117,
                  98,
                  115,
                  99,
                  114,
                  105,
                  112,
                  116,
                  105,
                  111,
                  110
                ]
              },
              {
                "kind": "account",
                "path": "config"
              },
              {
                "kind": "account",
                "path": "user"
              }
            ]
          }
        },
        {
          "name": "userTokenAccount",
          "writable": true
        },
        {
          "name": "treasuryTokenAccount",
          "writable": true
        },
        {
          "name": "keeperRewardTokenAccount",
          "writable": true,
          "optional": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    {
      "name": "createPlan",
      "discriminator": [
        77,
        43,
        141,
        254,
        212,
        118,
        41,
        186
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true
        },
        {
          "name": "admin",
          "writable": true,
          "signer": true,
          "relations": [
            "config"
          ]
        },
        {
          "name": "plan",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  112,
                  108,
                  97,
                  110
                ]
              },
              {
                "kind": "account",
                "path": "config"
              },
              {
                "kind": "account",
                "path": "config.planCount",
                "account": "config"
              }
            ]
          }
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "price",
          "type": "u64"
        },
        {
          "name": "interval",
          "type": "i64"
        },
        {
          "name": "gracePeriod",
          "type": "i64"
        }
      ],
      "returns": "u64"
    },
    {
      "name": "expireOverdue",
      "discriminator": [
        22,
        173,
        97,
        135,
        24,
        61,
        148,
        229
      ],
      "accounts": [
        {
          "name": "config",
          "relations": [
            "plan",
            "subscription"
          ]
        },
        {
          "name": "user"
        },
        {
          "name": "plan",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  112,
                  108,
                  97,
                  110
                ]
              },
              {
                "kind": "account",
                "path": "config"
              },
              {
                "kind": "account",
                "path": "subscription.planId",
                "account": "subscription"
              }
            ]
          }
        },
        {
          "name": "subscription",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  115,
                  117,
                  98,
                  115,
                  99,
                  114,
                  105,
                  112,
                  116,
                  105,
                  111,
                  110
                ]
              },
              {
                "kind": "account",
                "path": "config"
              },
              {
                "kind": "account",
                "path": "user"
              }
            ]
          }
        }
      ],
      "args": []
    },
    {
      "name": "initialize",
      "discriminator": [
        175,
        175,
        109,
        31,
        13,
        152,
        155,
        237
      ],
      "accounts": [
        {
          "name": "admin",
          "writable": true,
          "signer": true
        },
        {
          "name": "paymentMint"
        },
        {
          "name": "treasuryTokenAccount"
        },
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              },
              {
                "kind": "account",
                "path": "paymentMint"
              }
            ]
          }
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "keeperRewardBps",
          "type": "u16"
        }
      ]
    },
    {
      "name": "pause",
      "discriminator": [
        211,
        22,
        221,
        251,
        74,
        121,
        193,
        47
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true
        },
        {
          "name": "admin",
          "signer": true,
          "relations": [
            "config"
          ]
        }
      ],
      "args": []
    },
    {
      "name": "payNow",
      "discriminator": [
        82,
        130,
        249,
        185,
        242,
        44,
        221,
        97
      ],
      "accounts": [
        {
          "name": "config",
          "relations": [
            "plan",
            "subscription"
          ]
        },
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "plan",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  112,
                  108,
                  97,
                  110
                ]
              },
              {
                "kind": "account",
                "path": "config"
              },
              {
                "kind": "account",
                "path": "subscription.planId",
                "account": "subscription"
              }
            ]
          }
        },
        {
          "name": "subscription",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  115,
                  117,
                  98,
                  115,
                  99,
                  114,
                  105,
                  112,
                  116,
                  105,
                  111,
                  110
                ]
              },
              {
                "kind": "account",
                "path": "config"
              },
              {
                "kind": "account",
                "path": "user"
              }
            ]
          }
        },
        {
          "name": "userTokenAccount",
          "writable": true
        },
        {
          "name": "treasuryTokenAccount",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    {
      "name": "rescueToken",
      "discriminator": [
        227,
        248,
        168,
        149,
        165,
        80,
        20,
        89
      ],
      "accounts": [
        {
          "name": "config"
        },
        {
          "name": "admin",
          "signer": true,
          "relations": [
            "config"
          ]
        },
        {
          "name": "from",
          "writable": true
        },
        {
          "name": "to",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "retryCharge",
      "discriminator": [
        157,
        184,
        244,
        164,
        226,
        129,
        126,
        103
      ],
      "accounts": [
        {
          "name": "config",
          "relations": [
            "plan",
            "subscription"
          ]
        },
        {
          "name": "user"
        },
        {
          "name": "plan",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  112,
                  108,
                  97,
                  110
                ]
              },
              {
                "kind": "account",
                "path": "config"
              },
              {
                "kind": "account",
                "path": "subscription.planId",
                "account": "subscription"
              }
            ]
          }
        },
        {
          "name": "subscription",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  115,
                  117,
                  98,
                  115,
                  99,
                  114,
                  105,
                  112,
                  116,
                  105,
                  111,
                  110
                ]
              },
              {
                "kind": "account",
                "path": "config"
              },
              {
                "kind": "account",
                "path": "user"
              }
            ]
          }
        },
        {
          "name": "userTokenAccount",
          "writable": true
        },
        {
          "name": "treasuryTokenAccount",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    {
      "name": "setKeeperRewardBps",
      "discriminator": [
        54,
        20,
        4,
        86,
        126,
        217,
        218,
        97
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true
        },
        {
          "name": "admin",
          "signer": true,
          "relations": [
            "config"
          ]
        }
      ],
      "args": [
        {
          "name": "bps",
          "type": "u16"
        }
      ]
    },
    {
      "name": "setPlanActive",
      "discriminator": [
        215,
        87,
        208,
        194,
        87,
        65,
        181,
        5
      ],
      "accounts": [
        {
          "name": "config",
          "relations": [
            "plan"
          ]
        },
        {
          "name": "admin",
          "signer": true,
          "relations": [
            "config"
          ]
        },
        {
          "name": "plan",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "active",
          "type": "bool"
        }
      ]
    },
    {
      "name": "setTreasury",
      "discriminator": [
        57,
        97,
        196,
        95,
        195,
        206,
        106,
        136
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true
        },
        {
          "name": "admin",
          "signer": true,
          "relations": [
            "config"
          ]
        },
        {
          "name": "newTreasuryTokenAccount"
        }
      ],
      "args": []
    },
    {
      "name": "subscribe",
      "discriminator": [
        254,
        28,
        191,
        138,
        156,
        179,
        183,
        53
      ],
      "accounts": [
        {
          "name": "config",
          "relations": [
            "plan"
          ]
        },
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "plan"
        },
        {
          "name": "subscription",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  115,
                  117,
                  98,
                  115,
                  99,
                  114,
                  105,
                  112,
                  116,
                  105,
                  111,
                  110
                ]
              },
              {
                "kind": "account",
                "path": "config"
              },
              {
                "kind": "account",
                "path": "user"
              }
            ]
          }
        },
        {
          "name": "userTokenAccount",
          "writable": true
        },
        {
          "name": "treasuryTokenAccount",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": []
    },
    {
      "name": "unpause",
      "discriminator": [
        169,
        144,
        4,
        38,
        10,
        141,
        188,
        255
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true
        },
        {
          "name": "admin",
          "signer": true,
          "relations": [
            "config"
          ]
        }
      ],
      "args": []
    }
  ],
  "accounts": [
    {
      "name": "config",
      "discriminator": [
        155,
        12,
        170,
        224,
        30,
        250,
        204,
        130
      ]
    },
    {
      "name": "plan",
      "discriminator": [
        161,
        231,
        251,
        119,
        2,
        12,
        162,
        2
      ]
    },
    {
      "name": "subscription",
      "discriminator": [
        64,
        7,
        26,
        135,
        102,
        132,
        98,
        33
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "unauthorized",
      "msg": "Only the config admin can perform this action"
    },
    {
      "code": 6001,
      "name": "zeroPrice",
      "msg": "Price must be greater than zero"
    },
    {
      "code": 6002,
      "name": "intervalTooShort",
      "msg": "Interval is too short"
    },
    {
      "code": 6003,
      "name": "planNotActive",
      "msg": "Plan is not active"
    },
    {
      "code": 6004,
      "name": "invalidPlan",
      "msg": "Plan does not belong to this config"
    },
    {
      "code": 6005,
      "name": "alreadySubscribed",
      "msg": "User is already subscribed (Active or Overdue)"
    },
    {
      "code": 6006,
      "name": "notActive",
      "msg": "Subscription is not Active"
    },
    {
      "code": 6007,
      "name": "notOverdue",
      "msg": "Subscription is not Overdue"
    },
    {
      "code": 6008,
      "name": "notDueYet",
      "msg": "Subscription is not due for charging yet"
    },
    {
      "code": 6009,
      "name": "stillInsufficient",
      "msg": "Balance or delegated amount is still insufficient"
    },
    {
      "code": 6010,
      "name": "gracePeriodNotPassed",
      "msg": "Grace period has not passed yet"
    },
    {
      "code": 6011,
      "name": "rewardTooHigh",
      "msg": "Keeper reward bps exceeds the maximum allowed"
    },
    {
      "code": 6012,
      "name": "cannotRescuePaymentMint",
      "msg": "The payment mint can never be rescued from here — pull-payment design never lets this program hold a payment_mint balance"
    },
    {
      "code": 6013,
      "name": "invalidRescueSource",
      "msg": "Rescue source token account must be owned by the config PDA"
    },
    {
      "code": 6014,
      "name": "contractPaused",
      "msg": "Program is paused"
    },
    {
      "code": 6015,
      "name": "missingKeeperRewardAccount",
      "msg": "A keeper reward token account is required when this config's keeper_reward_bps > 0"
    },
    {
      "code": 6016,
      "name": "mintMismatch",
      "msg": "Token account mint does not match the config's payment mint"
    },
    {
      "code": 6017,
      "name": "invalidUserTokenAccount",
      "msg": "Token account owner does not match the expected user"
    },
    {
      "code": 6018,
      "name": "invalidTreasuryAccount",
      "msg": "Treasury token account does not match config.treasury_token_account"
    }
  ],
  "types": [
    {
      "name": "config",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "admin",
            "type": "pubkey"
          },
          {
            "name": "paymentMint",
            "type": "pubkey"
          },
          {
            "name": "treasuryTokenAccount",
            "type": "pubkey"
          },
          {
            "name": "keeperRewardBps",
            "type": "u16"
          },
          {
            "name": "paused",
            "type": "bool"
          },
          {
            "name": "planCount",
            "type": "u64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "plan",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "config",
            "type": "pubkey"
          },
          {
            "name": "planId",
            "type": "u64"
          },
          {
            "name": "price",
            "type": "u64"
          },
          {
            "name": "interval",
            "type": "i64"
          },
          {
            "name": "gracePeriod",
            "type": "i64"
          },
          {
            "name": "active",
            "type": "bool"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "subStatus",
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "inactive"
          },
          {
            "name": "active"
          },
          {
            "name": "overdue"
          },
          {
            "name": "expired"
          }
        ]
      }
    },
    {
      "name": "subscription",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "config",
            "type": "pubkey"
          },
          {
            "name": "planId",
            "type": "u64"
          },
          {
            "name": "status",
            "type": {
              "defined": {
                "name": "subStatus"
              }
            }
          },
          {
            "name": "nextChargeAt",
            "type": "i64"
          },
          {
            "name": "overdueSince",
            "type": "i64"
          },
          {
            "name": "periodsPaid",
            "type": "u64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    }
  ],
  "constants": [
    {
      "name": "configSeed",
      "type": "bytes",
      "value": "[99, 111, 110, 102, 105, 103]"
    },
    {
      "name": "planSeed",
      "type": "bytes",
      "value": "[112, 108, 97, 110]"
    },
    {
      "name": "subscriptionSeed",
      "type": "bytes",
      "value": "[115, 117, 98, 115, 99, 114, 105, 112, 116, 105, 111, 110]"
    }
  ]
};
